apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fullnameOverride }}-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
      - get
      - update
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - patch
      - get
      - update
      - list
  - apiGroups:
      - ''
    resources:
      - namespaces
      - services
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.fullnameOverride }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fullnameOverride }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride }}-sa
    namespace: {{ .Release.Namespace }}
    